[package]
name = "toml_edit_dll"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "toml"

[dependencies]
libc="0.2.146"
toml_edit="0.19.10"
labview-interop = { version = "0.2" }
