name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        build-type:
          - debug
          - release
        include:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
            shared-lib-extension: so
          - target: x86_64-pc-windows-msvc
            runs-on: windows-latest
            shared-lib-extension: dll
          - target: i686-pc-windows-msvc
            runs-on: windows-latest
            shared-lib-extension: dll

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        rustup target add ${{ matrix.target }}
        cargo build --target=${{ matrix.target }} --verbose --${{ matrix.build-type }}
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: |
          target/${{ matrix.target }}/${{ matrix.build-type }}/*toml.${{ matrix.shared-lib-extension }}
