name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  BUILD_TYPE: release

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
            shared-lib-extension: so
          - target: x86_64-pc-windows-msvc
            runs-on: windows-latest
            shared-lib-extension: dll
          - target: i686-pc-windows-msvc
            runs-on: windows-latest
            shared-lib-extension: dll
          - target: x86_64-apple-darwin
            runs-on: macos-latest
            shared-lib-extension: framework.zip

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        rustup target add ${{ matrix.target }}
        cargo build --target=${{ matrix.target }} --verbose --${{ env.BUILD_TYPE }}
    - name: Bundle Framework
      if: ${{ matrix.target == 'x86_64-apple-darwin' }}
      run: |
        BUILD_TYPE=release
        SHARED_LIBARY_NAME=libtoml.dylib
        BUILD_OUTPUT_DIR=$SCRIPT_DIR/target/$BUILD_TYPE
        FRAMEWORK_NAME=dragon_toml_64
        pushd $BUILD_OUTPUT_DIR
        rm -rf $FRAMEWORK_NAME.framework
        mkdir -p $FRAMEWORK_NAME.framework/Versions/A
        cp $SHARED_LIBARY_NAME $FRAMEWORK_NAME.framework/Versions/A/$FRAMEWORK_NAME
        chmod ugo+rx $FRAMEWORK_NAME.framework/Versions/A/$FRAMEWORK_NAME
        ln -s ./A ./$FRAMEWORK_NAME.framework/Versions/Current
        ln -s ./Versions/A/$FRAMEWORK_NAME ./$FRAMEWORK_NAME.framework
        rm -rf $FRAMEWORK_NAME.framework.zip
        zip -r $FRAMEWORK_NAME.framework.zip $FRAMEWORK_NAME.framework
        popd

    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        if-no-files-found: error
        path: |
          target/${{ matrix.target }}/${{ env.BUILD_TYPE }}/*.${{ matrix.shared-lib-extension }}
